<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGc6f8jc\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGc6f8jc/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerGc6f8jc.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerGc6f8jc\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerGc6f8jc\appAppKernelProdContainer([
    'container.build_hash' => 'Gc6f8jc',
    'container.build_id' => 'b5f0828b',
    'container.build_time' => 1708071529,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGc6f8jc');
